Admin overview
kir-dev/sprint-review-app pull request #19
Opened 2024-11-13 16:37 UTC by IvnDmnks

added filters

2024-11-16 18:14 UTC, FearsomeRover requested changes
Szuper lett. Kértem changeket, de nem nagyok. Amit még meg kéne oldani, segítek benne szívesen, hogy a usernél meg a projektnél inkább a usernevet meg a projekt nevet kapjuk vissza. Ehhez a backendes endpointot is módosítani kell viszont majd. A layout szerintem tök jó így.

2024-11-16 18:14 UTC, FearsomeRover commented on apps/frontend/src/app/(with-layout)/adminoverview/page.tsx
> +import AdminOverview from '../../../components/AdminOverview';
Ezt kicsit nehéz követni. Erre megoldás, hogy a tsconfig.jsonba felvesszük a path propertyt a compileroptionsön belülre. Ez ebben a projektben pont rosszul lett megoldva.
Le kell cserélni az értékét
`"paths": {
      "@/*": ["./src/*"]
    }`
   Ezek után már tudod így használni az importokat:
   `@/components/AdminOverview`

2024-11-16 18:14 UTC, FearsomeRover commented on apps/frontend/src/app/(with-layout)/layout.tsx
Same, mint az admin overviewnál.

2024-11-16 18:14 UTC, FearsomeRover commented on apps/frontend/src/components/AdminOverview.tsx
> +  console.log(sort);
Ezt majd kiveszed légyszi.

2024-11-16 18:14 UTC, FearsomeRover commented on apps/frontend/src/components/AdminOverview.tsx
> +      console.log(res.data);
Meg ezt is

2024-11-20 18:33 UTC, IvnDmnks commented on apps/frontend/src/app/(with-layout)/layout.tsx
Átírtam az összesnél, amit eddig csináltam. Nem csak ennél a kettőnél.

2024-11-20 18:38 UTC, IvnDmnks commented
Megcsináltam a változtatásokat.

2026-02-14 10:09 UTC, closed without merging